#!/bin/bash

# GCP env vars
export GCP_PROJECT=<YOUR VALUE>
export REGION=<YOUR VALUE>
export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json

# MySQL env vars
export MYSQL_INSTANCE=<YOUR VALUE>
export MYSQL_CONNECTION_NAME=$GCP_PROJECT:$REGION:$MYSQL_INSTANCE
export MYSQL_USER=<YOUR VALUE>
export MYSQL_PASS=<YOUR VALUE>
export MYSQL_DB=<YOUR VALUE>

# PostgreSQL env vars
export POSTGRESQL_INSTANCE=<YOUR VALUE>
export POSTGRES_CONNECTION_NAME=$GCP_PROJECT:$REGION:$POSTGRESQL_INSTANCE
export POSTGRES_USER=<YOUR VALUE>
export POSTGRES_PASS=<YOUR VALUE>
export POSTGRES_DB=<YOUR VALUE>

# SQL Server env vars
export SQL_INSTANCE=<YOUR VALUE>
export SQLSERVER_CONNECTION_NAME=$GCP_PROJECT:$REGION:$SQL_INSTANCE
export SQLSERVER_USER=<YOUR VALUE>
export SQLSERVER_PASS=<YOUR VALUE>
export SQLSERVER_DB=<YOUR VALUE>

# Python env vars
export FLASK_DEBUG=<YOUR VALUE>
