apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
  namespace: dev-namespace
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
