apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: dev-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - env:
            - name: REACT_APP_API_BASE_URL
              value: /api/
            - name: NODE_ENV
              value: production
          image: us.gcr.io/cloud-course-gdsc/client:v1.0
          imagePullPolicy: IfNotPresent
          name: client
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "275m"
              memory: "300Mi"
            limits:
              cpu: "750m"
              memory: "2000Mi"
      imagePullSecrets:
        - name: gcr-secret
