apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
  namespace: dev-namespace
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
