#!/bin/bash

# GCP env vars
export GCP_PROJECT=<YOUR VALUE>
export REGION=<YOUR VALUE>
export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json

# PostgreSQL env vars
export POSTGRESQL_INSTANCE=<YOUR VALUE>
export POSTGRES_CONNECTION_NAME=$GCP_PROJECT:$REGION:$POSTGRESQL_INSTANCE
export POSTGRES_USER=<YOUR VALUE>
export POSTGRES_PASS=<YOUR VALUE>
export POSTGRES_DB=<YOUR VALUE>

# Python env vars
export FLASK_DEBUG=<YOUR VALUE>
